spring: 
  profiles: prod
  datasource: #数据源
    base: 
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.18.30:3306/jdatax?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: iesapp
      initialSize: 0 
      maxActive: 20 
      maxIdle: 10 
      maxWait: 80 
      validationQuery: SELECT 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 7200000
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      defaultAutoCommit: true
      logAbandoned: true
mybatis: 
  mapper-locations: classpath:mapper/**/*Mapper.xml
  
logging:
  file: ../log.log
         
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
     
  


