#   默认的profile为test，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar JDataX.jar --spring.profiles.active=dev 
#   测试环境：java -jar JDataX.jar --spring.profiles.active=test  
#   生产环境：java -jar JDataX.jar --spring.profiles.active=prod  
spring:  
  profiles:  
    active: dev